name: weather-api

services:
  api:
    build: .  # Builds from your Dockerfile
    ports:
      - "8000:8000"  # Expose API to your browser
    environment:
      - REDIS_HOST=redis  # ‚Üê Points to Redis container!
      - API_KEY=${API_KEY}
    depends_on:
      - redis  # Start Redis first
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: